function param_vector = construct_std_param_vector_sym(...
        inertia_xx_joint, inertia_yy_joint, inertia_zz_joint, inertia_xy_joint, inertia_yz_joint,...
        inertia_zx_joint, link_mass, link_x_com, link_y_com, link_z_com, num_links)
    param_vector = sym(zeros(10 * num_links, 1));
    I_mat_joint_joint = sym(zeros(3, 3, num_links));
    I_vec_joint_joint = sym(zeros(6, num_links));
    link_com_link_frame_position_link_frame = sym(zeros(3, num_links));
    for curr_link_index = 1 : num_links
        I_mat_joint_joint(:, :, curr_link_index) = ...
            [inertia_xx_joint(curr_link_index) inertia_xy_joint(curr_link_index) inertia_zx_joint(curr_link_index); ...
             inertia_xy_joint(curr_link_index) inertia_yy_joint(curr_link_index) inertia_yz_joint(curr_link_index); ...
             inertia_zx_joint(curr_link_index) inertia_yz_joint(curr_link_index) inertia_zz_joint(curr_link_index)];
        link_com_link_frame_position_link_frame(:, curr_link_index) = ...
                                        [link_x_com(curr_link_index);...
                                        link_y_com(curr_link_index);...
                                        link_z_com(curr_link_index)];
        I_vec_joint_joint(:, curr_link_index) = inertia_mat_to_vec(I_mat_joint_joint(:, :, curr_link_index));
        param_vector(10 * (curr_link_index - 1) + 1 : 10 * (curr_link_index), :) = ...
            [I_vec_joint_joint(:, curr_link_index); ...
             link_mass(curr_link_index); ...
             link_mass(curr_link_index) * link_com_link_frame_position_link_frame(:, curr_link_index)];
    end
end