function rot_mat = DH_to_rot_mat(joint_twist, joint_position)
    rot_mat = [cos(joint_position)                   -sin(joint_position)                     0; ...
               sin(joint_position) * cos(joint_twist) cos(joint_position) * cos(joint_twist) -sin(joint_twist); ... 
               sin(joint_position) * sin(joint_twist) cos(joint_position) * sin(joint_twist)  cos(joint_twist)];
end